-- Naqlk SEO Editorial Rollout v1
-- Generated from scripts/seo/editorial-rollout-v1.mjs.
-- Maximum same-locale editorial Jaccard similarity: 0.374 (AHB/en / ABT/en).
begin;

create temporary table editorial_rollout_v1 (
  city_code text not null,
  locale text not null,
  slug text not null,
  seo_title text not null,
  meta_description text not null,
  page_heading text not null,
  introduction text not null,
  service_area_content text not null,
  neighborhood_coverage_text text not null,
  faqs jsonb not null,
  primary key(city_code,locale)
) on commit drop;

insert into editorial_rollout_v1 values
  ('JED','ar','jeddah','خدمات نقل منظمة داخل جدة وبين المدن | نقلك','أرسل طلب نقل أثاث أو بضائع في جدة عبر نقلك، وحدد العناوين والخدمات الإضافية ليُراجع الفريق التفاصيل ويرسل عرض سعر واضحاً قبل التنفيذ.','خدمات نقل الأثاث والبضائع في جدة','تخدم نقلك طلبات النقل المؤهلة في جدة بمسار يبدأ من معلومات عملية لا من وعود عامة. يحدد العميل موقع الاستلام والتسليم وطبيعة الأثاث أو البضائع وموعده المفضل، ثم يراجع الفريق البيانات ليقترح ترتيباً قابلاً للتنفيذ وعرض سعر واضحاً.','يمكن طلب نقل الأثاث أو البضائع العامة داخل جدة، أو تقديم طلب رحلة إلى مدينة أخرى متاحة ضمن نطاق التشغيل. تساعد ملاحظات المبنى، وحجم القطع، والحاجة إلى التغليف أو التحميل والتنزيل على تقييم الخدمة المناسبة؛ ولا تُضاف أي خدمة اختيارية قبل ظهورها كبند في العرض.','تُقيّم العناوين في جدة حسب الموقع الفعلي وسهولة الوصول ومساحة توقف المركبة، لذلك لا تفترض الصفحة تغطية كل حي أو صلاحية كل عنوان قبل المراجعة.','[{"question":"هل يمكن طلب نقل داخل جدة؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل جدة. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":10},{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب جدة؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في جدة. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":20},{"question":"كيف أتابع طلب النقل الخاص بي في جدة؟","answer":"بعد الإرسال تحصل على مرجع يبدأ بـ NQ. استخدم المرجع مع رقم الجوال في صفحة التتبع للاطلاع على المعلومات المتاحة للعميل دون عرض التفاصيل الداخلية.","displayOrder":30}]'::jsonb),
  ('JED','en','jeddah','Organized Furniture and Goods Transport in Jeddah | Naqlk','Submit a furniture or goods transport request in Jeddah, add access and optional-service details, and receive a reviewed quotation before execution.','Furniture and goods transport in Jeddah','Naqlk handles eligible Jeddah transport requests through a practical review rather than a generic promise. Customers identify the pickup and delivery points, describe the furniture or goods, and provide a preferred date so the team can assess the request and prepare a clear quotation.','Requests may cover furniture moving, general goods transport within Jeddah, or an intercity journey to a destination enabled in the current scope. Building access, item size, and optional packing or loading support are reviewed, and any approved option is shown as a separate quotation item.','Jeddah addresses are assessed individually for location accuracy, vehicle access, and a workable stopping point. The page does not imply that every district or property is automatically serviceable.','[{"question":"Can I request transport within Jeddah?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Jeddah. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":10},{"question":"Can I add packing or loading support to a Jeddah request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Jeddah request. The reviewed quotation identifies the approved service items before execution.","displayOrder":20},{"question":"How can I track my Jeddah transport request?","answer":"The confirmation provides an NQ reference. Use it with the submitted mobile number on the tracking page to view the customer-safe status without exposing internal operational details.","displayOrder":30}]'::jsonb),
  ('MKK','ar','makkah','طلب نقل الأثاث والبضائع في مكة المكرمة | نقلك','رتّب طلب نقل داخل مكة المكرمة أو إلى وجهة متاحة عبر نقلك، مع وصف الحمولة والعناوين ومراجعة الطلب قبل إرسال عرض السعر.','ترتيب خدمات النقل في مكة المكرمة','في مكة المكرمة تتأثر خطة النقل بدقة العنوان ووقت الوصول وطبيعة المبنى بقدر تأثرها بنوع المنقولات. يتيح نموذج نقلك جمع هذه التفاصيل في طلب واحد، ثم يراجعها فريق المبيعات لتحديد ما إذا كانت الخدمة والموعد المطلوبان قابلين للتنفيذ.','تشمل الخيارات المتاحة نقل الأثاث والبضائع العامة والنقل المحلي، مع إمكانية تقديم طلب بين المدن عندما تكون الوجهة مفعلة. يمكن إضافة التغليف أو المساعدة في التحميل والتنزيل عند الحاجة، وتظل تفاصيل التنفيذ خاضعة لمراجعة الحمولة والوصول وتوفر الموارد.','لا تُفترض قابلية الوصول إلى كل موقع في مكة المكرمة. يفيد إدخال اسم الشارع ووصف المدخل والطابق وأقرب معلم في تقييم العنوان وتجنب معلومات تغطية مضللة.','[{"question":"كيف أحصل على عرض سعر لخدمة نقل في مكة المكرمة؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب مكة المكرمة. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":10},{"question":"هل يمكن طلب نقل داخل مكة المكرمة؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل مكة المكرمة. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":20},{"question":"هل أحتاج إلى حساب لإرسال طلب نقل في مكة المكرمة؟","answer":"لا يلزم إنشاء حساب لإرسال الطلب. يمكنك تقديم بيانات طلب مكة المكرمة كزائر، ثم استخدام رقم الطلب NQ ورقم الجوال في مسار التتبع المخصص.","displayOrder":30}]'::jsonb),
  ('MKK','en','makkah','Plan Furniture and Goods Transport in Makkah | Naqlk','Arrange an eligible Makkah transport request with clear cargo, address, access, and timing details, followed by review and an itemized quotation.','Plan transport services in Makkah','A Makkah transport plan depends on accurate address, access, timing, and building information as much as the items being moved. Naqlk collects those details in one request and has Sales review them before confirming whether the requested service and schedule are workable.','Available request types include furniture moving, general goods transport, and local journeys, plus intercity requests when the destination is enabled. Optional packing and loading or unloading support can be requested, while final execution details remain subject to cargo, access, and resource review.','No Makkah address is assumed to be automatically reachable. Street, entrance, floor, and landmark notes help the team assess the location without publishing misleading blanket-coverage claims.','[{"question":"How do I request a transport quotation in Makkah?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Makkah request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":10},{"question":"Can I request transport within Makkah?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Makkah. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":20},{"question":"Do I need an account to submit a Makkah request?","answer":"No account is required. You can submit the Makkah request as a guest and later use the NQ request reference with the submitted mobile number through the dedicated tracking flow.","displayOrder":30}]'::jsonb),
  ('MED','ar','madinah','خدمة نقل واضحة في المدينة المنورة | نقلك','اطلب نقل الأثاث أو البضائع في المدينة المنورة، وأضف تفاصيل الوصول والخدمات الاختيارية لتحصل على عرض سعر بعد مراجعة الطلب.','خدمات نقل مدروسة في المدينة المنورة','تساعد نقلك سكان المدينة المنورة والمنشآت فيها على تحويل احتياج النقل إلى طلب منظم. يبدأ ذلك بوصف المنقولات والعنوانين وتوقيت الخدمة، مع إرفاق الصور عند فائدتها، حتى يستطيع الفريق فهم النطاق قبل تقديم أي التزام أو تسعير.','يمكن تقديم طلب لنقل الأثاث أو البضائع العامة داخل المدينة المنورة، كما يمكن طلب النقل إلى مدينة مفعلة أخرى. تتوفر خيارات التغليف والتحميل والتنزيل عند اختيارها وموافقة الفريق عليها، ويبين عرض السعر الكميات والبنود والضريبة والإجمالي قبل الاعتماد.','تظل الخدمة مرتبطة بعنواني الطلب الفعليين ومتطلبات الدخول والتوقف. لا تعني إتاحة المدينة المنورة تشغيلياً أن جميع المواقع أو الأوقات مقبولة دون مراجعة.','[{"question":"هل تتوفر خدمة النقل من المدينة المنورة إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من المدينة المنورة إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":10},{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب المدينة المنورة؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في المدينة المنورة. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":20},{"question":"كيف أحصل على عرض سعر لخدمة نقل في المدينة المنورة؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب المدينة المنورة. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":30}]'::jsonb),
  ('MED','en','madinah','Clear Transport Requests in Madinah | Naqlk','Request furniture or goods transport in Madinah and provide access, timing, and optional-service details for review before a quotation is issued.','Reviewed transport services in Madinah','Naqlk helps households and businesses in Madinah turn a transport need into a structured request. Describing the items, both addresses, timing, and useful photos gives the team enough context to understand the scope before making a commitment or issuing a price.','Customers can request furniture moving or general goods transport within Madinah, as well as transport to another enabled city. Packing and loading or unloading remain optional and are included only after review; the quotation then shows quantities, line items, VAT, and the total.','Service depends on the actual pickup and delivery locations, entry conditions, and a practical vehicle stopping point. Operational availability in Madinah does not mean every site or time is accepted without review.','[{"question":"Can I request transport from Madinah to another city?","answer":"You can request an intercity journey from Madinah to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":10},{"question":"Can I add packing or loading support to a Madinah request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Madinah request. The reviewed quotation identifies the approved service items before execution.","displayOrder":20},{"question":"How do I request a transport quotation in Madinah?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Madinah request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":30}]'::jsonb),
  ('DMM','ar','dammam','نقل الأثاث والبضائع في الدمام بخطوات واضحة | نقلك','قدّم طلب نقل محلي أو بين المدن من الدمام مع بيانات الحمولة والعناوين، ودع فريق نقلك يراجع النطاق ويرسل عرضاً مفصلاً.','حلول طلب النقل في الدمام','تخدم الدمام احتياجات منزلية وتجارية متنوعة، ولهذا تعتمد نقلك على تفاصيل الطلب بدلاً من افتراض نموذج واحد لكل عملية نقل. يوضح العميل نوع المنقولات والكميات التقريبية ونقاط الاستلام والتسليم، ثم تتم مراجعة الملاءمة والموعد قبل عرض السعر.','يدعم المسار طلبات نقل الأثاث والبضائع العامة داخل الدمام، وطلبات النقل إلى مدينة أخرى مفعلة. يمكن تحديد الحاجة إلى التغليف أو التحميل والتنزيل، بينما تبقى طبيعة الحمولة وحجمها وإمكانية الوصول عوامل أساسية في اعتماد الخدمة وتحديد بنودها.','تُراجع مواقع الدمام وفق بيانات الخريطة والعنوان المكتوب وملاحظات البوابة أو المصعد أو منطقة التوقف. لا تُعرض قائمة أحياء مصطنعة ولا وعد بتغطية شاملة.','[{"question":"هل يمكن طلب نقل داخل الدمام؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل الدمام. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":10},{"question":"هل تتوفر خدمة النقل من الدمام إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من الدمام إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":20},{"question":"كيف أتابع طلب النقل الخاص بي في الدمام؟","answer":"بعد الإرسال تحصل على مرجع يبدأ بـ NQ. استخدم المرجع مع رقم الجوال في صفحة التتبع للاطلاع على المعلومات المتاحة للعميل دون عرض التفاصيل الداخلية.","displayOrder":30}]'::jsonb),
  ('DMM','en','dammam','Structured Furniture and Goods Transport in Dammam | Naqlk','Submit a local or intercity Dammam transport request with cargo and address details for scope review and a transparent itemized quotation.','Structured transport requests in Dammam','Dammam includes varied household and commercial transport needs, so Naqlk assesses the actual request instead of assuming one model fits every move. Customers describe the items, approximate quantities, pickup point, and destination before suitability and timing are reviewed.','The flow supports furniture moving and general goods transport within Dammam, along with requests to another enabled city. Packing and loading or unloading can be selected, while cargo type, volume, and site access remain central to approval and the quotation line items.','Dammam locations are reviewed using map coordinates, the written address, and notes about gates, lifts, or vehicle stopping space. No fabricated district list or blanket coverage promise is published.','[{"question":"Can I request transport within Dammam?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Dammam. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":10},{"question":"Can I request transport from Dammam to another city?","answer":"You can request an intercity journey from Dammam to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":20},{"question":"How can I track my Dammam transport request?","answer":"The confirmation provides an NQ reference. Use it with the submitted mobile number on the tracking page to view the customer-safe status without exposing internal operational details.","displayOrder":30}]'::jsonb),
  ('KHO','ar','al-khobar','ترتيب نقل الأثاث والبضائع في الخبر | نقلك','نظّم طلب نقل في الخبر عبر نموذج يجمع العناوين وتفاصيل المنقولات والخدمات الإضافية، ثم استلم عرض سعر بعد مراجعة الفريق.','خدمات نقل مرنة للطلبات في الخبر','تبدأ عملية النقل الجيدة في الخبر بوصف واضح لما يجب نقله وكيفية الوصول إلى الموقعين. تجمع نقلك بيانات الأثاث أو البضائع والعناوين والتوقيت والملاحظات في طلب واحد، ليتحقق الفريق من النطاق قبل إعداد العرض وخطة التنفيذ.','يمكن للعملاء طلب النقل داخل الخبر أو تقديم رحلة إلى مدينة متاحة أخرى، سواء للأثاث أو للبضائع العامة المؤهلة. تساعد صور القطع والكميات وملاحظات الطوابق في تحديد الاحتياج، ويمكن إدراج التغليف والتحميل والتنزيل كخيارات مستقلة عند اعتمادها.','يُقيّم كل عنوان في الخبر على حدة، بما في ذلك مدخل المبنى ومساحة الحركة وموقع وقوف المركبة. لا تعتمد نقلك على تعميم واحد للمناطق السكنية والتجارية.','[{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب الخبر؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في الخبر. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":10},{"question":"كيف أحصل على عرض سعر لخدمة نقل في الخبر؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب الخبر. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":20},{"question":"هل أحتاج إلى حساب لإرسال طلب نقل في الخبر؟","answer":"لا يلزم إنشاء حساب لإرسال الطلب. يمكنك تقديم بيانات طلب الخبر كزائر، ثم استخدام رقم الطلب NQ ورقم الجوال في مسار التتبع المخصص.","displayOrder":30}]'::jsonb),
  ('KHO','en','al-khobar','Arrange Furniture and Goods Transport in Al Khobar | Naqlk','Organize an Al Khobar transport request with addresses, item details, and optional support, then receive a quotation after team review.','Flexible transport requests in Al Khobar','A well-planned move in Al Khobar begins with a clear description of the items and access at both sites. Naqlk combines cargo, address, timing, and access notes in one request so the team can confirm the scope before preparing a quotation and execution plan.','Customers may request transport within Al Khobar or a journey to another enabled city for eligible furniture and general goods. Item photos, quantities, and floor notes improve the review, while packing and loading or unloading can appear as separate options when approved.','Each Al Khobar address is assessed individually, including building entrance, movement space, and vehicle stopping conditions. Naqlk does not apply one blanket assumption to residential and commercial locations.','[{"question":"Can I add packing or loading support to a Al Khobar request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Al Khobar request. The reviewed quotation identifies the approved service items before execution.","displayOrder":10},{"question":"How do I request a transport quotation in Al Khobar?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Al Khobar request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":20},{"question":"Do I need an account to submit a Al Khobar request?","answer":"No account is required. You can submit the Al Khobar request as a guest and later use the NQ request reference with the submitted mobile number through the dedicated tracking flow.","displayOrder":30}]'::jsonb),
  ('DHA','ar','dhahran','طلبات نقل الأثاث والبضائع في الظهران | نقلك','أرسل طلب نقل داخل الظهران أو إلى مدينة متاحة، مع وصف المنقولات والوصول لتتم مراجعته وإصدار عرض سعر واضح.','تنظيم طلب النقل في الظهران','تعتمد نقلك في الظهران على عنوان دقيق ووصف واقعي للمنقولات قبل اقتراح التنفيذ. يمكن للعميل توضيح نقطة الاستلام والوجهة والكميات التقريبية وأي قيود دخول، ما يساعد على تقليل الافتراضات عند مراجعة الطلب.','يدعم النموذج نقل الأثاث والبضائع العامة والنقل المحلي، إضافة إلى طلبات بين المدن للوجهات المفعلة. لا يشمل ذلك تلقائياً أعمال النقل الصناعي المتخصص؛ فكل حمولة تُراجع وفق طبيعتها، وتظهر خدمات التغليف أو التحميل والتنزيل في العرض عند مناسبتها.','تُقبل الطلبات في الظهران بحسب صلاحية العنوان والوصول والتوقيت وتوفر الموارد. إدراج إحداثيات الموقع ووصف البوابة يساعد أكثر من الاعتماد على اسم المنطقة وحده.','[{"question":"هل يمكن طلب نقل داخل الظهران؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل الظهران. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":10},{"question":"كيف أحصل على عرض سعر لخدمة نقل في الظهران؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب الظهران. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":20},{"question":"كيف أتابع طلب النقل الخاص بي في الظهران؟","answer":"بعد الإرسال تحصل على مرجع يبدأ بـ NQ. استخدم المرجع مع رقم الجوال في صفحة التتبع للاطلاع على المعلومات المتاحة للعميل دون عرض التفاصيل الداخلية.","displayOrder":30}]'::jsonb),
  ('DHA','en','dhahran','Furniture and Goods Transport Requests in Dhahran | Naqlk','Submit a Dhahran local or enabled intercity transport request with accurate item and access details for review and clear pricing.','Organize a transport request in Dhahran','Naqlk relies on an accurate Dhahran address and a realistic item description before proposing execution. Customers can identify the pickup point, destination, approximate quantities, and any entry restrictions, reducing assumptions during the request review.','The form supports furniture moving, general goods transport, local journeys, and intercity requests to enabled destinations. It does not automatically cover specialized industrial haulage; every load is assessed, with packing or loading and unloading listed only when suitable.','Dhahran requests are accepted according to address suitability, access, timing, and available resources. Map coordinates and gate notes are more useful than relying on the area name alone.','[{"question":"Can I request transport within Dhahran?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Dhahran. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":10},{"question":"How do I request a transport quotation in Dhahran?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Dhahran request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":20},{"question":"How can I track my Dhahran transport request?","answer":"The confirmation provides an NQ reference. Use it with the submitted mobile number on the tracking page to view the customer-safe status without exposing internal operational details.","displayOrder":30}]'::jsonb),
  ('AHS','ar','al-ahsa','خدمات نقل مدروسة في الأحساء | نقلك','اطلب نقل الأثاث أو البضائع في الأحساء مع تحديد الموقعين وطبيعة الحمولة، واستلم عرضاً بعد مراجعة الوصول والخدمة المطلوبة.','خدمات نقل الأثاث والبضائع في الأحساء','اتساع النطاق العمراني في الأحساء يجعل تحديد نقطة الاستلام والتسليم بدقة خطوة مهمة. يتيح طلب نقلك إضافة الإحداثيات والعنوان الوصفي وتفاصيل الحمولة، حتى يراجع الفريق المسافة والوصول ومتطلبات الخدمة قبل التأكيد.','تشمل الطلبات المؤهلة نقل الأثاث والبضائع العامة داخل الأحساء، أو رحلة إلى مدينة أخرى مفعلة عند توفرها. يمكن اختيار التغليف والتحميل والتنزيل حسب الحاجة، ويظل العرض النهائي مرتبطاً بالكميات الفعلية وطبيعة المواقع والموعد المطلوب.','لا تستخدم الصفحة أسماء مناطق فرعية غير موثقة لإيحاء بتغطية أوسع. تُراجع كل نقطة في الأحساء باستخدام بيانات العنوان التي يرسلها العميل ونطاق التشغيل الحالي.','[{"question":"هل تتوفر خدمة النقل من الأحساء إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من الأحساء إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":10},{"question":"هل أحتاج إلى حساب لإرسال طلب نقل في الأحساء؟","answer":"لا يلزم إنشاء حساب لإرسال الطلب. يمكنك تقديم بيانات طلب الأحساء كزائر، ثم استخدام رقم الطلب NQ ورقم الجوال في مسار التتبع المخصص.","displayOrder":20},{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب الأحساء؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في الأحساء. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":30}]'::jsonb),
  ('AHS','en','al-ahsa','Reviewed Furniture and Goods Transport in Al Ahsa | Naqlk','Request furniture or goods transport in Al Ahsa with precise locations and cargo details, followed by an access and service review.','Furniture and goods transport in Al Ahsa','Al Ahsa''s broad urban area makes precise pickup and delivery points especially useful. A Naqlk request can include coordinates, a written address, and cargo details so the team can assess distance, access, and service requirements before confirmation.','Eligible requests include furniture moving and general goods transport within Al Ahsa, or a journey to another enabled city when available. Packing and loading or unloading are optional, while final quotation items depend on actual quantities, locations, and the requested schedule.','The page does not use unverified sub-area lists to imply wider coverage. Each Al Ahsa point is reviewed using customer-provided address data and the current operating scope.','[{"question":"Can I request transport from Al Ahsa to another city?","answer":"You can request an intercity journey from Al Ahsa to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":10},{"question":"Do I need an account to submit a Al Ahsa request?","answer":"No account is required. You can submit the Al Ahsa request as a guest and later use the NQ request reference with the submitted mobile number through the dedicated tracking flow.","displayOrder":20},{"question":"Can I add packing or loading support to a Al Ahsa request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Al Ahsa request. The reviewed quotation identifies the approved service items before execution.","displayOrder":30}]'::jsonb),
  ('JUB','ar','jubail','نقل الأثاث والبضائع العامة في الجبيل | نقلك','قدّم طلب نقل مؤهل في الجبيل للأثاث أو البضائع العامة، مع مراجعة طبيعة الحمولة والعناوين قبل إصدار عرض السعر.','خدمات النقل العام للأثاث والبضائع في الجبيل','تتعامل نقلك في الجبيل مع احتياجات نقل الأثاث والبضائع العامة المؤهلة، مع فصل واضح بينها وبين النقل الصناعي المتخصص غير المشمول. يصف العميل الحمولة والاستخدام المطلوب والعنوانين، ثم يراجع الفريق ملاءمة الخدمة قبل التسعير.','يمكن تقديم طلب داخل الجبيل أو إلى وجهة مفعلة بين المدن. تُستخدم الكمية والأبعاد والصور وملاحظات الموقع لتقييم المركبة والجهد المطلوب، وقد تضاف خدمات التغليف أو التحميل والتنزيل بعد المراجعة؛ ولا تشمل الخدمة المعلنة الجمارك أو الشحن الدولي أو مناولة المعدات الثقيلة.','ترتبط إمكانية التنفيذ بالمواقع الفعلية ونوع المنقولات وشروط الدخول. لا تُعد الإتاحة التشغيلية في الجبيل موافقة مسبقة على المواقع الصناعية أو المقيدة.','[{"question":"كيف أحصل على عرض سعر لخدمة نقل في الجبيل؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب الجبيل. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":10},{"question":"هل تتوفر خدمة النقل من الجبيل إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من الجبيل إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":20},{"question":"هل يمكن طلب نقل داخل الجبيل؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل الجبيل. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":30}]'::jsonb),
  ('JUB','en','jubail','Furniture and General Goods Transport in Jubail | Naqlk','Submit an eligible Jubail furniture or general-goods request, with cargo and address suitability reviewed before a quotation is issued.','Furniture and general goods transport in Jubail','Naqlk serves eligible furniture and general-goods needs in Jubail while keeping them distinct from unsupported specialist industrial haulage. Customers describe the load, intended service, and both addresses before the team reviews suitability and prepares pricing.','A request may be within Jubail or to an enabled intercity destination. Quantities, dimensions, photos, and site notes help assess the required transport and effort, with packing or loading support added after review. Customs, international shipping, and heavy-equipment handling are not claimed here.','Execution depends on the actual sites, cargo type, and entry conditions. Jubail''s operational status is not advance approval for industrial or otherwise restricted locations.','[{"question":"How do I request a transport quotation in Jubail?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Jubail request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":10},{"question":"Can I request transport from Jubail to another city?","answer":"You can request an intercity journey from Jubail to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":20},{"question":"Can I request transport within Jubail?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Jubail. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":30}]'::jsonb),
  ('TAI','ar','taif','تنظيم نقل الأثاث والبضائع في الطائف | نقلك','أرسل طلب نقل داخل الطائف أو إلى مدينة مفعلة، وشارك تفاصيل الطريق والوصول والحمولة للحصول على عرض مدروس.','خدمات نقل منظمة في الطائف','يساعد وصف الموقع وطبيعة الوصول في الطائف على بناء خطة نقل أكثر دقة، خصوصاً عندما تختلف مداخل المباني أو ظروف الطريق. تجمع نقلك هذه الملاحظات مع بيانات المنقولات والموعد، ثم تراجع الطلب قبل اقتراح التنفيذ.','يمكن طلب نقل الأثاث أو البضائع العامة داخل الطائف، كما يمكن تقديم طلب بين المدن إلى وجهة متاحة. يفيد توضيح القطع الكبيرة والطوابق ومساحة الوقوف في تحديد الاحتياج، ويمكن طلب التغليف والتحميل والتنزيل كبنود اختيارية وليست افتراضاً ثابتاً.','تُراجع نقاط الطائف حسب الإحداثيات والعنوان والوصول الفعلي، بما في ذلك أي ملاحظة طريق يقدمها العميل. لا تقدم الصفحة ضماناً عاماً لكل موقع أو موعد.','[{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب الطائف؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في الطائف. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":10},{"question":"كيف أتابع طلب النقل الخاص بي في الطائف؟","answer":"بعد الإرسال تحصل على مرجع يبدأ بـ NQ. استخدم المرجع مع رقم الجوال في صفحة التتبع للاطلاع على المعلومات المتاحة للعميل دون عرض التفاصيل الداخلية.","displayOrder":20},{"question":"هل تتوفر خدمة النقل من الطائف إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من الطائف إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":30}]'::jsonb),
  ('TAI','en','taif','Organized Furniture and Goods Transport in Taif | Naqlk','Submit a Taif local or enabled intercity request with road, access, and cargo details for a considered quotation and plan.','Organized transport services in Taif','Location and access information helps create a more accurate Taif transport plan, particularly where building entrances or road conditions differ. Naqlk combines those notes with item and timing details, then reviews the request before proposing execution.','Customers can request furniture moving or general goods transport within Taif, as well as an intercity journey to an available destination. Large items, floors, and stopping space help define the need, while packing and loading or unloading remain optional quotation items.','Taif points are assessed using coordinates, the written address, and any road-access note supplied by the customer. The page does not guarantee every location or time in advance.','[{"question":"Can I add packing or loading support to a Taif request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Taif request. The reviewed quotation identifies the approved service items before execution.","displayOrder":10},{"question":"How can I track my Taif transport request?","answer":"The confirmation provides an NQ reference. Use it with the submitted mobile number on the tracking page to view the customer-safe status without exposing internal operational details.","displayOrder":20},{"question":"Can I request transport from Taif to another city?","answer":"You can request an intercity journey from Taif to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":30}]'::jsonb),
  ('TUU','ar','tabuk','طلب نقل محلي وبين المدن من تبوك | نقلك','نظّم طلب نقل أثاث أو بضائع في تبوك، وحدد العنوان والوجهة والحمولة ليتم تقييم النطاق وإرسال عرض سعر قبل التنفيذ.','خدمات نقل قابلة للمراجعة في تبوك','توفر نقلك لتبوك مساراً واضحاً لطلب النقل يبدأ بالبيانات الأساسية وينتهي بعرض يمكن مراجعته. يحدد العميل نوع الخدمة والحمولة والعنوانين والتاريخ المرغوب، ما يسمح للفريق بتقييم رحلة المدينة أو المسافة بين المدن دون افتراضات.','تشمل الطلبات الممكنة نقل الأثاث والبضائع العامة داخل تبوك، ورحلات إلى وجهات مفعلة عند قبولها. لأن مسافة الرحلة والموارد تختلف، تتم مراجعة النقل بين المدن لكل طلب، كما تُدرج خدمات التغليف والتحميل والتنزيل فقط إذا اختارها العميل واعتمدت.','يعتمد نطاق تبوك الفعلي على نقطة الاستلام والتسليم وملاءمة الوصول والموعد. لا تعني صفحة المدينة وجود جدول ثابت لكل وجهة أو تغطية غير محدودة.','[{"question":"هل أحتاج إلى حساب لإرسال طلب نقل في تبوك؟","answer":"لا يلزم إنشاء حساب لإرسال الطلب. يمكنك تقديم بيانات طلب تبوك كزائر، ثم استخدام رقم الطلب NQ ورقم الجوال في مسار التتبع المخصص.","displayOrder":10},{"question":"كيف أحصل على عرض سعر لخدمة نقل في تبوك؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب تبوك. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":20},{"question":"هل تتوفر خدمة النقل من تبوك إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من تبوك إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":30}]'::jsonb),
  ('TUU','en','tabuk','Local and Intercity Transport Requests from Tabuk | Naqlk','Organize furniture or goods transport in Tabuk with destination, cargo, and address details reviewed before execution and pricing.','Reviewed transport services in Tabuk','Naqlk gives Tabuk customers a clear transport-request path that starts with essential information and ends with a reviewable quotation. Service type, cargo, addresses, and preferred date allow the team to assess a local or intercity journey without assumptions.','Possible requests include furniture moving and general goods transport within Tabuk, plus journeys to enabled destinations when accepted. Because distance and resources vary, intercity requests are reviewed individually, and packing or loading support is listed only when selected and approved.','The practical Tabuk scope depends on pickup, delivery, access suitability, and timing. A city page does not imply a fixed schedule to every destination or unlimited coverage.','[{"question":"Do I need an account to submit a Tabuk request?","answer":"No account is required. You can submit the Tabuk request as a guest and later use the NQ request reference with the submitted mobile number through the dedicated tracking flow.","displayOrder":10},{"question":"How do I request a transport quotation in Tabuk?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Tabuk request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":20},{"question":"Can I request transport from Tabuk to another city?","answer":"You can request an intercity journey from Tabuk to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":30}]'::jsonb),
  ('AHB','ar','abha','خدمات نقل تراعي تفاصيل الوصول في أبها | نقلك','قدّم طلب نقل أثاث أو بضائع في أبها مع وصف الموقع والوصول والقطع، ليُراجع الفريق الخدمة ويرسل عرضاً واضحاً.','تنظيم خدمات النقل في أبها','تجعل طبيعة أبها المرتفعة وتنوع الوصول بين المواقع من تفاصيل الطريق والمدخل جزءاً مهماً من طلب النقل. تتيح نقلك إضافة الإحداثيات ووصف المبنى والقطع المراد نقلها حتى تتم مراجعة الحالة الفعلية بدلاً من الاعتماد على اسم المدينة فقط.','يدعم المسار نقل الأثاث والبضائع العامة داخل أبها، وطلبات بين المدن عندما تكون الوجهة ضمن النطاق المفعّل. يمكن اختيار التغليف أو التحميل والتنزيل، وتساعد معلومات القطع الكبيرة والطوابق ومساحة الحركة في تحديد بنود العرض والموارد المناسبة.','لا تدعي نقلك الوصول التلقائي إلى كل موقع في أبها. تُراجع العناوين وملاحظات الطريق والتوقف لكل طلب، وقد يتطلب الفريق معلومات إضافية قبل التأكيد.','[{"question":"هل يمكن طلب نقل داخل أبها؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل أبها. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":10},{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب أبها؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في أبها. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":20},{"question":"كيف أحصل على عرض سعر لخدمة نقل في أبها؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب أبها. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":30}]'::jsonb),
  ('AHB','en','abha','Transport Planned Around Access Details in Abha | Naqlk','Submit an Abha furniture or goods request with location, access, and item details so the team can review service and provide a clear quotation.','Plan transport services in Abha','Abha''s elevated setting and varied site access make road and entrance details an important part of a transport request. Naqlk lets customers add coordinates, building notes, and item information so the real location is reviewed rather than relying on the city name alone.','The flow supports furniture moving and general goods transport within Abha, with intercity requests when the destination is enabled. Packing or loading and unloading can be selected, while large-item, floor, and movement-space details help determine quotation items and suitable resources.','Naqlk does not claim automatic access to every Abha location. Addresses, road notes, and stopping conditions are reviewed for each request, and the team may ask for additional information.','[{"question":"Can I request transport within Abha?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Abha. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":10},{"question":"Can I add packing or loading support to a Abha request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Abha request. The reviewed quotation identifies the approved service items before execution.","displayOrder":20},{"question":"How do I request a transport quotation in Abha?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Abha request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":30}]'::jsonb),
  ('KMX','ar','khamis-mushait','نقل الأثاث والبضائع في خميس مشيط | نقلك','اطلب نقل الأثاث أو البضائع في خميس مشيط عبر مسار يجمع العناوين والحمولة والموعد، ثم راجع عرض السعر قبل الاعتماد.','خدمات نقل واضحة في خميس مشيط','يمنح طلب نقلك في خميس مشيط الفريق صورة عملية عن النقل المطلوب قبل تحديد الحل. يضيف العميل نوع الخدمة وموقعي الاستلام والتسليم ووصف المنقولات والموعد، مع ملاحظات الوصول التي قد تؤثر في الوقوف أو حركة القطع.','يمكن استخدام المسار لنقل الأثاث أو البضائع العامة داخل خميس مشيط، أو لطلب رحلة إلى مدينة أخرى متاحة. تُراجع الخدمات الاختيارية مثل التغليف والتحميل والتنزيل مع الحمولة، ويظل عرض السعر المرجع لبنود الخدمة والضريبة والإجمالي.','تُحدد قابلية الخدمة في خميس مشيط من واقع العنوانين ونطاق التشغيل وتوفر الموارد. لا تنشر الصفحة قائمة أحياء غير موثقة أو وعداً مسبقاً لكل طلب.','[{"question":"كيف أتابع طلب النقل الخاص بي في خميس مشيط؟","answer":"بعد الإرسال تحصل على مرجع يبدأ بـ NQ. استخدم المرجع مع رقم الجوال في صفحة التتبع للاطلاع على المعلومات المتاحة للعميل دون عرض التفاصيل الداخلية.","displayOrder":10},{"question":"هل تتوفر خدمة النقل من خميس مشيط إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من خميس مشيط إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":20},{"question":"هل أحتاج إلى حساب لإرسال طلب نقل في خميس مشيط؟","answer":"لا يلزم إنشاء حساب لإرسال الطلب. يمكنك تقديم بيانات طلب خميس مشيط كزائر، ثم استخدام رقم الطلب NQ ورقم الجوال في مسار التتبع المخصص.","displayOrder":30}]'::jsonb),
  ('KMX','en','khamis-mushait','Clear Furniture and Goods Transport in Khamis Mushait | Naqlk','Request Khamis Mushait transport through a flow that captures addresses, cargo, and timing before you review the quotation.','Clear transport services in Khamis Mushait','A Naqlk request in Khamis Mushait gives the team a practical view of the needed transport before a solution is selected. Customers add service type, pickup and delivery locations, item details, timing, and access notes that may affect parking or item movement.','The flow can be used for furniture or general goods within Khamis Mushait, or for a request to another available city. Optional packing and loading or unloading are reviewed with the cargo, while the quotation remains the authority for service items, VAT, and total.','Service feasibility in Khamis Mushait is based on the addresses, current operating scope, and resource availability. No unverified district list or advance acceptance promise is published.','[{"question":"How can I track my Khamis Mushait transport request?","answer":"The confirmation provides an NQ reference. Use it with the submitted mobile number on the tracking page to view the customer-safe status without exposing internal operational details.","displayOrder":10},{"question":"Can I request transport from Khamis Mushait to another city?","answer":"You can request an intercity journey from Khamis Mushait to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":20},{"question":"Do I need an account to submit a Khamis Mushait request?","answer":"No account is required. You can submit the Khamis Mushait request as a guest and later use the NQ request reference with the submitted mobile number through the dedicated tracking flow.","displayOrder":30}]'::jsonb),
  ('ELQ','ar','buraidah','ترتيب نقل الأثاث والبضائع في بريدة | نقلك','أرسل تفاصيل طلب النقل في بريدة للأثاث أو البضائع، واختر الدعم الإضافي عند الحاجة لتحصل على عرض بعد المراجعة.','خدمات نقل منظمة في بريدة','تساعد نقلك العملاء في بريدة على وصف احتياج النقل بطريقة تقلل الغموض عند التسعير. تشمل البيانات العناوين ونوع القطع والكميات التقريبية والتاريخ، ويمكن إضافة صور أو ملاحظات للمداخل عندما تسهم في تقييم الطلب.','يدعم النظام النقل داخل بريدة للأثاث والبضائع العامة، كما يقبل طلبات بين المدن للوجهات المفعلة. يختار العميل التغليف أو التحميل والتنزيل عند الحاجة، ثم يراجع الفريق هذه الخيارات مع تفاصيل الحمولة قبل إصدار عرض البنود النهائي.','تُراجع نقاط بريدة بشكل مستقل وفق دقة الموقع وإمكانية الوصول والموارد المتوفرة في التاريخ المطلوب. لا تُفهم الإتاحة كضمان لكل حي أو مبنى.','[{"question":"كيف أحصل على عرض سعر لخدمة نقل في بريدة؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب بريدة. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":10},{"question":"هل يمكن طلب نقل داخل بريدة؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل بريدة. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":20},{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب بريدة؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في بريدة. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":30}]'::jsonb),
  ('ELQ','en','buraidah','Arrange Furniture and Goods Transport in Buraidah | Naqlk','Send Buraidah furniture or goods request details, select optional support when needed, and receive a quotation after review.','Organized transport services in Buraidah','Naqlk helps Buraidah customers describe a transport need in a way that reduces uncertainty during pricing. Addresses, item types, approximate quantities, and date are captured, with photos or entrance notes added when they improve the assessment.','The system supports furniture and general-goods transport within Buraidah and accepts intercity requests to enabled destinations. Customers select packing or loading and unloading when needed, then the team reviews those options with the cargo before issuing the final line-item quotation.','Buraidah points are reviewed independently using location accuracy, access feasibility, and resources available for the requested date. Operational availability is not a guarantee for every district or building.','[{"question":"How do I request a transport quotation in Buraidah?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Buraidah request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":10},{"question":"Can I request transport within Buraidah?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Buraidah. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":20},{"question":"Can I add packing or loading support to a Buraidah request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Buraidah request. The reviewed quotation identifies the approved service items before execution.","displayOrder":30}]'::jsonb),
  ('HAS','ar','hail','طلبات نقل الأثاث والبضائع في حائل | نقلك','قدّم طلب نقل داخل حائل أو إلى وجهة مفعلة مع العناوين ووصف الحمولة، واحصل على عرض سعر مدروس قبل التنفيذ.','خدمات نقل قابلة للتخطيط في حائل','توفر نقلك في حائل نموذجاً يجمع ما يحتاجه الفريق لتقييم عملية النقل دون اتصالات متفرقة. يوضح العميل الخدمة المطلوبة وموقعي الرحلة والمنقولات والتوقيت، ثم تتم مراجعة المعلومات لإعداد نطاق مفهوم وعرض سعر قابل للمراجعة.','يمكن إرسال طلب للأثاث أو البضائع العامة داخل حائل، أو طلب نقل بين المدن إلى وجهة متاحة. تختلف متطلبات الرحلات بحسب المسافة والحمولة، لذلك يُراجع كل طلب منفرداً، وتضاف خدمات التغليف والتحميل والتنزيل عندما تكون مطلوبة ومناسبة.','يُحدد نطاق العمل من العناوين الفعلية والوصول والجدول المتاح، لا من اسم حائل وحده. لا يوجد في الصفحة ادعاء بجدول رحلات ثابت أو تغطية كل موقع.','[{"question":"هل تتوفر خدمة النقل من حائل إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من حائل إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":10},{"question":"كيف أتابع طلب النقل الخاص بي في حائل؟","answer":"بعد الإرسال تحصل على مرجع يبدأ بـ NQ. استخدم المرجع مع رقم الجوال في صفحة التتبع للاطلاع على المعلومات المتاحة للعميل دون عرض التفاصيل الداخلية.","displayOrder":20},{"question":"كيف أحصل على عرض سعر لخدمة نقل في حائل؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب حائل. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":30}]'::jsonb),
  ('HAS','en','hail','Plan Furniture and Goods Transport in Hail | Naqlk','Submit local or enabled intercity transport in Hail with addresses and cargo details, then receive a reviewed quotation before execution.','Transport services you can plan in Hail','Naqlk provides a Hail request form that gathers what the team needs to assess a move without fragmented conversations. Customers identify the service, journey points, items, and timing before the information is reviewed into a clear scope and quotation.','Furniture and general-goods requests may be submitted within Hail or to an available intercity destination. Journey requirements vary with distance and cargo, so each request is assessed individually, with packing and loading or unloading added when needed and suitable.','The working scope comes from actual addresses, access, and an available schedule rather than the Hail name alone. This page does not claim fixed departures or coverage of every location.','[{"question":"Can I request transport from Hail to another city?","answer":"You can request an intercity journey from Hail to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":10},{"question":"How can I track my Hail transport request?","answer":"The confirmation provides an NQ reference. Use it with the submitted mobile number on the tracking page to view the customer-safe status without exposing internal operational details.","displayOrder":20},{"question":"How do I request a transport quotation in Hail?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Hail request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":30}]'::jsonb),
  ('YNB','ar','yanbu','نقل الأثاث والبضائع العامة في ينبع | نقلك','اطلب نقل الأثاث أو البضائع العامة في ينبع مع تحديد الحمولة والعناوين، ليتم فحص الملاءمة وإرسال عرض واضح.','خدمات نقل الأثاث والبضائع العامة في ينبع','تخدم نقلك طلبات الأثاث والبضائع العامة المؤهلة في ينبع، مع مراجعة طبيعة المنقولات بدقة قبل القبول. يرسل العميل العنوانين والوصف والكميات التقريبية وأي صور مفيدة، حتى لا تختلط الخدمة العامة بأعمال الموانئ أو الشحن المتخصص غير المعلن.','يشمل نطاق الطلب النقل داخل ينبع أو إلى مدينة أخرى مفعلة عند الموافقة. يمكن اختيار التغليف والتحميل والتنزيل، وتُحدد البنود حسب الحمولة والوصول؛ ولا تدعي الصفحة تقديم التخليص الجمركي أو الشحن الدولي أو خدمات التخزين.','تُراجع مواقع ينبع وفق عنوان الطلب الفعلي وشروط الدخول ووقوف المركبة. وجود المدينة في مناطق الخدمة لا يعني قبول مواقع مقيدة أو أنواع حمولة غير مدعومة.','[{"question":"هل يمكن طلب نقل داخل ينبع؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل ينبع. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":10},{"question":"هل أحتاج إلى حساب لإرسال طلب نقل في ينبع؟","answer":"لا يلزم إنشاء حساب لإرسال الطلب. يمكنك تقديم بيانات طلب ينبع كزائر، ثم استخدام رقم الطلب NQ ورقم الجوال في مسار التتبع المخصص.","displayOrder":20},{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب ينبع؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في ينبع. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":30}]'::jsonb),
  ('YNB','en','yanbu','Furniture and General Goods Transport in Yanbu | Naqlk','Request eligible furniture or general-goods transport in Yanbu with cargo and address details reviewed before a clear quotation.','Furniture and general goods transport in Yanbu','Naqlk serves eligible furniture and general-goods requests in Yanbu, with cargo type reviewed carefully before acceptance. Customers provide both addresses, descriptions, approximate quantities, and useful photos so the general service is not confused with unadvertised port or specialist freight work.','Requests may be within Yanbu or to another enabled city when approved. Packing and loading or unloading can be selected and quoted according to cargo and access. Customs clearance, international shipping, and warehousing are not claimed by this page.','Yanbu locations are reviewed using the actual request address, entry conditions, and vehicle stopping needs. Service-area status does not imply acceptance of restricted sites or unsupported cargo types.','[{"question":"Can I request transport within Yanbu?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Yanbu. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":10},{"question":"Do I need an account to submit a Yanbu request?","answer":"No account is required. You can submit the Yanbu request as a guest and later use the NQ request reference with the submitted mobile number through the dedicated tracking flow.","displayOrder":20},{"question":"Can I add packing or loading support to a Yanbu request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Yanbu request. The reviewed quotation identifies the approved service items before execution.","displayOrder":30}]'::jsonb),
  ('GIZ','ar','jazan','خدمات نقل الأثاث والبضائع في جازان | نقلك','نظّم طلب نقل في جازان من خلال بيانات واضحة للمنقولات والعنوانين، ثم استلم عرضاً بعد التحقق من النطاق والتوفر.','تنظيم طلبات النقل في جازان','تبدأ خدمة نقلك في جازان بطلب يوضح الحاجة بدلاً من وعد عام. يحدد العميل ما سينقله ومكان الاستلام والتسليم والتاريخ، ويضيف ملاحظات الوصول أو الصور عند الحاجة، ليتمكن الفريق من تقييم النطاق الفعلي.','يمكن طلب نقل الأثاث والبضائع العامة داخل جازان، أو تقديم رحلة إلى مدينة مفعلة ضمن التشغيل. تُراجع المسافة والحمولة والموعد قبل التأكيد، ويمكن أن يشمل العرض التغليف أو التحميل والتنزيل عندما يختارها العميل وتناسب الطلب.','تعتمد إمكانية التنفيذ في جازان على العناوين المحددة والوصول وتوفر الموارد. لا تقدم الصفحة وعداً بتغطية كل موقع في المنطقة أو جميع الوجهات.','[{"question":"كيف أحصل على عرض سعر لخدمة نقل في جازان؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب جازان. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":10},{"question":"كيف أتابع طلب النقل الخاص بي في جازان؟","answer":"بعد الإرسال تحصل على مرجع يبدأ بـ NQ. استخدم المرجع مع رقم الجوال في صفحة التتبع للاطلاع على المعلومات المتاحة للعميل دون عرض التفاصيل الداخلية.","displayOrder":20},{"question":"هل تتوفر خدمة النقل من جازان إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من جازان إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":30}]'::jsonb),
  ('GIZ','en','jazan','Furniture and Goods Transport Requests in Jazan | Naqlk','Organize a Jazan transport request with clear item and address details, then receive a quotation after scope and availability review.','Organize transport requests in Jazan','Naqlk service in Jazan begins with a request that explains the need rather than a blanket promise. Customers specify the items, pickup, delivery, and date, adding access notes or photos when useful so the team can evaluate the actual scope.','Furniture and general-goods transport can be requested within Jazan, or to a city enabled in the operating scope. Distance, cargo, and timing are reviewed before confirmation, with packing or loading and unloading added when selected and suitable.','Execution in Jazan depends on the specified addresses, access, and available resources. The page does not promise every location in the region or every destination.','[{"question":"How do I request a transport quotation in Jazan?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Jazan request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":10},{"question":"How can I track my Jazan transport request?","answer":"The confirmation provides an NQ reference. Use it with the submitted mobile number on the tracking page to view the customer-safe status without exposing internal operational details.","displayOrder":20},{"question":"Can I request transport from Jazan to another city?","answer":"You can request an intercity journey from Jazan to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":30}]'::jsonb),
  ('EAM','ar','najran','طلب نقل واضح للأثاث والبضائع في نجران | نقلك','أرسل طلب نقل في نجران مع العناوين والحمولة والخدمات الاختيارية، ليُراجع الفريق البيانات قبل عرض السعر والتنفيذ.','خدمات نقل واضحة في نجران','يمنح نموذج نقلك لطلبات نجران العميل طريقة مباشرة لتسجيل كل ما يؤثر في النقل. تشمل البيانات وصف الأثاث أو البضائع والموقعين والوقت المقترح ومتطلبات الدخول، وبذلك يستطيع الفريق مراجعة الطلب بصورة عملية.','يدعم النظام النقل المحلي داخل نجران وطلبات بين المدن إلى الوجهات المفعلة، للأثاث والبضائع العامة المؤهلة. يختار العميل التغليف أو التحميل والتنزيل عند الحاجة، ويعتمد العرض النهائي على تفاصيل الحمولة والعنوان وتوفر الموارد.','لا تُنشر ادعاءات بأن كل مواقع نجران متاحة تلقائياً. يُفحص كل عنوان ومسار طلب وفق المعلومات المقدمة ونطاق التشغيل في وقت المراجعة.','[{"question":"هل أحتاج إلى حساب لإرسال طلب نقل في نجران؟","answer":"لا يلزم إنشاء حساب لإرسال الطلب. يمكنك تقديم بيانات طلب نجران كزائر، ثم استخدام رقم الطلب NQ ورقم الجوال في مسار التتبع المخصص.","displayOrder":10},{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب نجران؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في نجران. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":20},{"question":"هل يمكن طلب نقل داخل نجران؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل نجران. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":30}]'::jsonb),
  ('EAM','en','najran','Clear Furniture and Goods Transport in Najran | Naqlk','Submit a Najran transport request with addresses, cargo, and optional services for team review before quotation and execution.','Clear transport services in Najran','The Naqlk form gives Najran customers a direct way to record each factor that affects transport. Item descriptions, both locations, proposed timing, and entry requirements allow the team to review the request on practical information.','The system supports local journeys within Najran and intercity requests to enabled destinations for eligible furniture and general goods. Customers may select packing or loading and unloading, while the final quotation depends on cargo, address, and resource availability.','No claim is made that every Najran location is automatically available. Each address and requested journey is checked against the submitted information and operating scope at review time.','[{"question":"Do I need an account to submit a Najran request?","answer":"No account is required. You can submit the Najran request as a guest and later use the NQ request reference with the submitted mobile number through the dedicated tracking flow.","displayOrder":10},{"question":"Can I add packing or loading support to a Najran request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Najran request. The reviewed quotation identifies the approved service items before execution.","displayOrder":20},{"question":"Can I request transport within Najran?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Najran. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":30}]'::jsonb),
  ('AKJ','ar','al-kharj','تنظيم النقل داخل الخرج وإلى المدن المتاحة | نقلك','قدّم طلب نقل أثاث أو بضائع في الخرج أو إلى وجهة مفعلة، مع مراجعة العناوين والنطاق وإرسال عرض قبل الاعتماد.','خدمات النقل داخل الخرج وبين المدن','تساعد نقلك في الخرج على تنظيم الطلبات المحلية والطلبات المتجهة إلى مدينة أخرى متاحة من خلال مسار واحد. يحدد العميل العنوانين وطبيعة المنقولات والتوقيت، ثم يراجع الفريق المسافة والوصول والخدمات المطلوبة.','تشمل الطلبات المؤهلة نقل الأثاث والبضائع العامة داخل الخرج، إضافة إلى النقل بين المدن عندما تكون الوجهة مفعلة. يمكن إضافة التغليف أو التحميل والتنزيل، وتظهر تفاصيل الكميات والأسعار والضريبة في العرض قبل قبول العميل.','يُراجع عنوان الخرج والوجهة الفعلية لكل طلب، ولا يُفترض القبول استناداً إلى قرب مدينة أخرى أو اسم المنطقة. الموعد النهائي مرتبط بالتوفر بعد المراجعة.','[{"question":"هل تتوفر خدمة النقل من الخرج إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من الخرج إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":10},{"question":"كيف أحصل على عرض سعر لخدمة نقل في الخرج؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب الخرج. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":20},{"question":"كيف أتابع طلب النقل الخاص بي في الخرج؟","answer":"بعد الإرسال تحصل على مرجع يبدأ بـ NQ. استخدم المرجع مع رقم الجوال في صفحة التتبع للاطلاع على المعلومات المتاحة للعميل دون عرض التفاصيل الداخلية.","displayOrder":30}]'::jsonb),
  ('AKJ','en','al-kharj','Transport Within Al Kharj and to Enabled Cities | Naqlk','Submit furniture or goods transport in Al Kharj or to an enabled destination, with addresses and scope reviewed before approval.','Local and intercity transport in Al Kharj','Naqlk helps Al Kharj customers organize local requests and journeys to another available city through one flow. Customers specify the addresses, items, and timing before the team assesses distance, access, and requested services.','Eligible requests include furniture and general-goods transport within Al Kharj, plus intercity transport when the destination is enabled. Packing or loading and unloading can be added, with quantities, pricing, VAT, and totals shown before customer acceptance.','The actual Al Kharj address and destination are reviewed for each request; acceptance is not inferred from proximity to another city or the region name. Final timing depends on availability after review.','[{"question":"Can I request transport from Al Kharj to another city?","answer":"You can request an intercity journey from Al Kharj to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":10},{"question":"How do I request a transport quotation in Al Kharj?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Al Kharj request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":20},{"question":"How can I track my Al Kharj transport request?","answer":"The confirmation provides an NQ reference. Use it with the submitted mobile number on the tracking page to view the customer-safe status without exposing internal operational details.","displayOrder":30}]'::jsonb),
  ('ARA','ar','arar','طلب نقل الأثاث والبضائع في عرعر | نقلك','أرسل طلب نقل محلي أو بين المدن من عرعر مع تفاصيل العنوان والحمولة، ليُراجع النطاق ويُرسل عرض سعر واضح.','خدمات نقل مدروسة في عرعر','تتيح نقلك لعملاء عرعر تسجيل احتياج النقل بمعلومات تساعد على اتخاذ قرار واقعي. يتضمن الطلب نوع الخدمة والعنوانين ووصف المنقولات والتاريخ المرغوب، مع إمكانية إضافة ملاحظات أو صور توضح الحجم والوصول.','يمكن تقديم طلب لنقل الأثاث أو البضائع العامة داخل عرعر أو إلى وجهة مفعلة أخرى. تُراجع رحلات المدن بحسب المسافة والموارد، بينما يبقى التغليف والتحميل والتنزيل اختيارياً ويظهر كبنود مستقلة عند اعتماده.','يعتمد قبول الخدمة في عرعر على المواقع الفعلية والوصول والتوقيت، ولا تُستنتج تغطية كل موقع أو وجهة من تفعيل المدينة في النموذج.','[{"question":"هل يمكن طلب نقل داخل عرعر؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل عرعر. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":10},{"question":"هل أحتاج إلى حساب لإرسال طلب نقل في عرعر؟","answer":"لا يلزم إنشاء حساب لإرسال الطلب. يمكنك تقديم بيانات طلب عرعر كزائر، ثم استخدام رقم الطلب NQ ورقم الجوال في مسار التتبع المخصص.","displayOrder":20},{"question":"كيف أحصل على عرض سعر لخدمة نقل في عرعر؟","answer":"أدخل عناوين الاستلام والتسليم ووصف المنقولات وأي ملاحظات وصول تخص طلب عرعر. يراجع ممثل المبيعات البيانات ثم يرسل عرضاً مفصلاً قبل اعتماد الطلب.","displayOrder":30}]'::jsonb),
  ('ARA','en','arar','Furniture and Goods Transport Requests in Arar | Naqlk','Submit local or intercity transport from Arar with address and cargo details so the scope can be reviewed and clearly quoted.','Reviewed transport services in Arar','Naqlk lets Arar customers record a transport need using information that supports a realistic decision. The request captures service type, both addresses, items, and preferred date, with notes or photos available to clarify size and access.','Customers can request furniture or general-goods transport within Arar or to another enabled destination. Intercity journeys are reviewed for distance and resources, while packing and loading or unloading remain optional and appear as separate approved items.','Service acceptance in Arar depends on the real locations, access, and timing. Activating the city in the request form does not imply every site or destination is covered.','[{"question":"Can I request transport within Arar?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Arar. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":10},{"question":"Do I need an account to submit a Arar request?","answer":"No account is required. You can submit the Arar request as a guest and later use the NQ request reference with the submitted mobile number through the dedicated tracking flow.","displayOrder":20},{"question":"How do I request a transport quotation in Arar?","answer":"Provide the pickup and delivery addresses, an accurate item description, and any access notes for the Arar request. A Sales representative reviews the details before sending an itemized quotation.","displayOrder":30}]'::jsonb),
  ('AJF','ar','sakaka','خدمات نقل منظمة للأثاث والبضائع في سكاكا | نقلك','نظّم طلب نقل في سكاكا مع بيانات المنقولات والوصول، واختر الخدمات الإضافية المناسبة قبل استلام عرض السعر.','تنظيم نقل الأثاث والبضائع في سكاكا','يركز مسار نقلك في سكاكا على المعلومات التي تحدد نطاق العمل فعلياً. يسجل العميل عناوين الرحلة ووصف القطع والكميات والموعد، ويضيف أي قيود عند البوابة أو داخل المبنى قبل أن يراجع الفريق الطلب.','تتوفر إمكانية طلب النقل المحلي للأثاث والبضائع العامة، أو تقديم طلب إلى مدينة مفعلة أخرى. يمكن اختيار التغليف والمساعدة في التحميل والتنزيل، وتُراجع هذه الخدمات مع حجم الحمولة حتى يعكس العرض العمل الموافق عليه فقط.','تُقيم نقاط سكاكا وفق الإحداثيات والعنوان وشروط الوصول في الوقت المطلوب. لا تدرج الصفحة مناطق فرعية أو مسارات غير موثقة لزيادة الانطباع بالتغطية.','[{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب سكاكا؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في سكاكا. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":10},{"question":"هل تتوفر خدمة النقل من سكاكا إلى مدينة أخرى؟","answer":"يمكن طلب رحلة بين المدن تبدأ من سكاكا إلى وجهة مفعلة في نطاق التشغيل. يخضع التأكيد لمراجعة نوع المنقولات والعناوين والموعد وتوفر الموارد المناسبة.","displayOrder":20},{"question":"كيف أتابع طلب النقل الخاص بي في سكاكا؟","answer":"بعد الإرسال تحصل على مرجع يبدأ بـ NQ. استخدم المرجع مع رقم الجوال في صفحة التتبع للاطلاع على المعلومات المتاحة للعميل دون عرض التفاصيل الداخلية.","displayOrder":30}]'::jsonb),
  ('AJF','en','sakaka','Organized Furniture and Goods Transport in Sakaka | Naqlk','Organize a Sakaka transport request with item and access data, selecting suitable optional services before the quotation.','Organize furniture and goods transport in Sakaka','The Naqlk flow in Sakaka focuses on information that defines the actual work. Customers record the journey addresses, items, quantities, and preferred date, adding any gate or building restrictions before the team reviews the request.','Furniture and general-goods transport can be requested locally or to another enabled city. Packing and loading or unloading may be selected, then assessed against cargo volume so the quotation reflects only the approved work.','Sakaka points are evaluated using coordinates, the written address, and access conditions for the requested time. No unverified sub-area or route list is published to inflate the impression of coverage.','[{"question":"Can I add packing or loading support to a Sakaka request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Sakaka request. The reviewed quotation identifies the approved service items before execution.","displayOrder":10},{"question":"Can I request transport from Sakaka to another city?","answer":"You can request an intercity journey from Sakaka to a destination enabled in the operating scope. Confirmation follows a review of the items, addresses, requested date, and suitable resources.","displayOrder":20},{"question":"How can I track my Sakaka transport request?","answer":"The confirmation provides an NQ reference. Use it with the submitted mobile number on the tracking page to view the customer-safe status without exposing internal operational details.","displayOrder":30}]'::jsonb),
  ('ABT','ar','al-bahah','خدمات نقل تراعي الوصول في الباحة | نقلك','اطلب نقل الأثاث أو البضائع في الباحة مع تفاصيل الطريق والمدخل والحمولة، ليتم تقييم التنفيذ وإرسال عرض واضح.','خدمات نقل مدروسة في الباحة','تفاصيل الطريق ومدخل الموقع مهمة عند التخطيط للنقل في الباحة ذات الطبيعة المرتفعة. يتيح نموذج نقلك إضافة إحداثيات دقيقة ووصف للمبنى والمنقولات، حتى يبني الفريق مراجعته على الموقع الحقيقي لا على افتراض عام.','يمكن طلب نقل الأثاث والبضائع العامة داخل الباحة، أو تقديم طلب رحلة إلى مدينة مفعلة عندما تسمح تفاصيل التشغيل. تساعد صور القطع والطوابق ومساحة التوقف في التقييم، ويمكن إدراج التغليف أو التحميل والتنزيل كخدمات اختيارية.','لا تعد الصفحة بأن كل طريق أو موقع في الباحة مناسب للمركبة. تُراجع ملاحظات الوصول والعنوان والتوقيت لكل طلب، وقد يحتاج الفريق إلى توضيح قبل اعتماد العرض.','[{"question":"هل يمكن طلب نقل داخل الباحة؟","answer":"نعم، يمكن إرسال طلب بين عنواني استلام وتسليم مؤهلين داخل الباحة. يراجع فريق نقلك تفاصيل الحمولة والعنوانين ومتطلبات الوصول قبل تأكيد إمكانية التنفيذ والموعد.","displayOrder":10},{"question":"هل يمكن إضافة التغليف أو التحميل والتنزيل لطلب الباحة؟","answer":"يمكن اختيار التغليف أو التحميل والتنزيل كخدمات إضافية عند تعبئة الطلب في الباحة. يراجع الفريق الاحتياج الفعلي ويبين البنود المعتمدة بوضوح في عرض السعر.","displayOrder":20},{"question":"هل أحتاج إلى حساب لإرسال طلب نقل في الباحة؟","answer":"لا يلزم إنشاء حساب لإرسال الطلب. يمكنك تقديم بيانات طلب الباحة كزائر، ثم استخدام رقم الطلب NQ ورقم الجوال في مسار التتبع المخصص.","displayOrder":30}]'::jsonb),
  ('ABT','en','al-bahah','Transport Planned for Access Conditions in Al Bahah | Naqlk','Request furniture or goods transport in Al Bahah with road, entrance, and cargo details reviewed before execution and quotation.','Reviewed transport services in Al Bahah','Road and entrance details matter when planning transport in Al Bahah''s elevated setting. The Naqlk form captures precise coordinates, building notes, and item information so the team reviews the real site instead of relying on a broad assumption.','Furniture and general-goods transport can be requested within Al Bahah, or to an enabled city when operating details allow. Item photos, floor information, and stopping space support assessment, with packing or loading and unloading available as optional services.','The page does not promise that every Al Bahah road or site suits the vehicle. Access notes, address, and timing are reviewed for each request, and clarification may be required before quotation approval.','[{"question":"Can I request transport within Al Bahah?","answer":"Yes. You can submit a request between eligible pickup and delivery addresses in Al Bahah. Naqlk reviews the load, both addresses, and access requirements before confirming availability and timing.","displayOrder":10},{"question":"Can I add packing or loading support to a Al Bahah request?","answer":"Packing and loading or unloading can be selected as optional services when you submit a Al Bahah request. The reviewed quotation identifies the approved service items before execution.","displayOrder":20},{"question":"Do I need an account to submit a Al Bahah request?","answer":"No account is required. You can submit the Al Bahah request as a guest and later use the NQ request reference with the submitted mobile number through the dedicated tracking flow.","displayOrder":30}]'::jsonb);

do $$
declare
  v_codes constant text[] := array['JED','MKK','MED','DMM','KHO','DHA','AHS','JUB','TAI','TUU','AHB','KMX','ELQ','HAS','YNB','GIZ','EAM','AKJ','ARA','AJF','ABT']::text[];
  v_dirty text;
begin
  if (select count(*) from editorial_rollout_v1) <> 42 then
    raise exception 'SEO editorial rollout must contain exactly 42 locale records';
  end if;

  if (select count(distinct city_code) from editorial_rollout_v1) <> 21 then
    raise exception 'SEO editorial rollout must contain exactly 21 cities';
  end if;

  if exists (
    select 1 from editorial_rollout_v1 r
    left join public.cities c on c.city_code=r.city_code and c.deleted_at is null
    where c.id is null or c.status<>'active'
  ) then
    raise exception 'SEO editorial rollout contains a missing or inactive Service Area city';
  end if;

  select string_agg(c.city_code||'/'||s.locale,', ' order by c.city_code,s.locale)
    into v_dirty
  from public.city_seo_contents s
  join public.cities c on c.id=s.city_id
  where c.city_code=any(v_codes)
    and (
      s.content_status<>'draft' or s.is_indexable or s.published_at is not null or s.version<>1
      or s.seo_title is not null or s.meta_description is not null or s.page_heading is not null
      or s.introduction is not null or s.service_area_content is not null
      or s.neighborhood_coverage_text is not null
      or s.created_by_profile_id is not null or s.updated_by_profile_id is not null
      or exists(select 1 from public.city_seo_faqs f where f.city_seo_content_id=s.id)
      or exists(select 1 from public.city_seo_routes p where p.city_seo_content_id=s.id)
    );

  if v_dirty is not null then
    raise exception 'SEO editorial rollout refuses to overwrite operator-managed content: %',v_dirty;
  end if;

  if (
    select count(*) from public.city_seo_contents s
    join public.cities c on c.id=s.city_id
    where c.city_code=any(v_codes) and s.locale in ('ar','en')
  ) <> 42 then
    raise exception 'SEO registry is missing an expected locale record';
  end if;
end $$;

update public.city_seo_contents s set
  slug=r.slug,
  seo_title=r.seo_title,
  meta_description=r.meta_description,
  page_heading=r.page_heading,
  introduction=r.introduction,
  service_area_content=r.service_area_content,
  neighborhood_coverage_text=r.neighborhood_coverage_text,
  updated_at=now()
from editorial_rollout_v1 r
join public.cities c on c.city_code=r.city_code
where s.city_id=c.id and s.locale=r.locale;

insert into public.city_seo_faqs(city_seo_content_id,question,answer,display_order)
select s.id,f.item->>'question',f.item->>'answer',(f.item->>'displayOrder')::integer
from editorial_rollout_v1 r
join public.cities c on c.city_code=r.city_code
join public.city_seo_contents s on s.city_id=c.id and s.locale=r.locale
cross join lateral jsonb_array_elements(r.faqs) f(item);

do $$
declare v_not_ready text;
begin
  select string_agg(c.city_code||'/'||s.locale||':'||array_to_string(private.city_seo_readiness_issues(s.id),','),'; ' order by c.city_code,s.locale)
    into v_not_ready
  from public.city_seo_contents s
  join public.cities c on c.id=s.city_id
  join editorial_rollout_v1 r on r.city_code=c.city_code and r.locale=s.locale
  where cardinality(private.city_seo_readiness_issues(s.id))<>0;

  if v_not_ready is not null then
    raise exception 'SEO editorial readiness failed: %',v_not_ready;
  end if;
end $$;

update public.city_seo_contents s set
  content_status='published',
  is_indexable=true,
  published_at=now(),
  updated_at=now(),
  version=version+1
from editorial_rollout_v1 r
join public.cities c on c.city_code=r.city_code
where s.city_id=c.id and s.locale=r.locale
  and cardinality(private.city_seo_readiness_issues(s.id))=0;

do $$
begin
  if (
    select count(*) from public.city_seo_contents s
    join public.cities c on c.id=s.city_id
    where c.status='active' and c.deleted_at is null
      and s.content_status='published' and s.is_indexable
      and cardinality(private.city_seo_readiness_issues(s.id))=0
  ) <> 44 then
    raise exception 'SEO editorial rollout did not produce 44 readiness-valid published locale records';
  end if;
end $$;

comment on table public.city_seo_contents is
  'Localized city SEO registry. Riyadh was seeded by SEO v1; the guarded Editorial Rollout v1 published the remaining approved locale records without bypassing Admin lifecycle controls.';

commit;
